### ISSUE TITLE
Row-majored or Column-majored

### ISSUE THREAD

**Issue by LeoLai930603** [tpoisonooo/how-to-optimize-gemm#4]
I found the definition of MMult0.c and MMult1.c for multi-dimensional array storage, would you like to take a look and see whether both of them are correct?
For MMult0.c
https://github.com/tpoisonooo/how-to-optimize-gemm/blob/ddab74e4ab57a5cda6d3b55c9e2f803719ec86e1/src/HowToOptimizeGemm/MMult0.c#L3-L5

For MMult1.c
https://github.com/tpoisonooo/how-to-optimize-gemm/blob/ddab74e4ab57a5cda6d3b55c9e2f803719ec86e1/src/HowToOptimizeGemm/MMult1.c#L3-L5

As you see, the positions of i and j are inverted.

**Comment by tpoisonooo** [comment]
Well, MMult1.c seems not correct, I would fix it latter.
Any PR would be well received.

**Comment by tpoisonooo** [comment]
Fixed.
