### ISSUE TITLE
question about gflops benchmark

### ISSUE THREAD

**Issue by Wanger-SJTU** [tpoisonooo/how-to-optimize-gemm#6]
gflops benchmark中的 `#define OP_FLOATS (80)`,  这里的80是怎么计算的呢？

**Comment by tpoisonooo** [comment]
.s 文件里面，每次循环 80 次乘加。

**Comment by jeezrick** [comment]
我的理解是四十次FMA计算，一次FMA包括一次乘法与一次加法，所以相当于两个float point operation，四十次FMA也就等于80flops。
