### ISSUE TITLE
Why 2 kernels in armv8/MMult_4x4_13?

### ISSUE THREAD

**Issue by Sh-Zh-7** [tpoisonooo/how-to-optimize-gemm#8]
Is that for performance reason or just comparison?

**Comment by tpoisonooo** [comment]
> Is that for performance reason or just comparison?

Just comparison. Use `#define KERNEL_4x4  kernel_4x4_v2` to change kernel implementation.

This is a bad code style, let me fix it later.

**Comment by tpoisonooo** [comment]
done.

**Comment by Sh-Zh-7** [comment]
你好，我最近正在摸鱼中，无法亲自回复你的邮件。我将在摸鱼结束后，尽快给你回复。
